n = input('Digite algo: ')
print('É numérico? ', n.isnumeric())
print('É alfanumérico? ', n.isalnum())
print('É letra? ', n.isalpha())
print('É decimal? ', n.isdecimal())
print('É minúsculo? ', n.islower())
print('É espaço? ', n.isspace())
print('É título? ', n.istitle())
print('É maiúsculo? ', n.isupper())